# Generated by Django 3.1.7 on 2021-03-01 17:06

import django.core.validators
from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=125, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=125, verbose_name='Имя')),
                ('patronymic_name', models.CharField(max_length=125, verbose_name='Отчество')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('inn', fernet_fields.fields.EncryptedIntegerField(verbose_name='ИНН')),
                ('phone_number', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{5,14}$')], verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Информации ползователя',
                'verbose_name_plural': 'Информация',
            },
        ),
    ]
